name: Build IPKs (24.10.0 x86_64 | SSR-Plus from kenzok8/small)

on:
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install host deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev python3 \
            unzip zlib1g-dev file wget rsync libelf-dev ccache tar xz-utils zstd jq

      - name: Download OpenWrt SDK (24.10.0 / x86_64, archive)
        run: |
          set -e
          BASE_URL="https://archive.openwrt.org/releases/24.10.0/targets/x86/64/"
          SDK_TAR="openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          wget -q "${BASE_URL}${SDK_TAR}" -O "${SDK_TAR}"
          tar --zstd -xf "${SDK_TAR}"
          echo "SDK_DIR=$(find . -maxdepth 1 -type d -name 'openwrt-sdk-*' | head -n1)" >> $GITHUB_ENV

      - name: (Optional) Cache dl to speed up
        uses: actions/cache@v4
        with:
          path: ${{ env.SDK_DIR }}/dl
          key: sdk-24.10.0-x86_64-dl-${{ hashFiles('.github/workflows/build-ipk-24.10.0-x86_64-ssrplus-small.yml') }}

      - name: Prepare feeds (24.10 branches + kenzok8/small only)
        run: |
          set -e
          cd "$SDK_DIR"
          cat > feeds.conf.default <<'EOF'
          src-git packages  https://git.openwrt.org/feed/packages.git;openwrt-24.10
          src-git luci      https://git.openwrt.org/project/luci.git;openwrt-24.10
          src-git routing   https://git.openwrt.org/feed/routing.git;openwrt-24.10
          src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-24.10
          src-git small     https://github.com/kenzok8/small-package.git;main
          EOF
          ./scripts/feeds update -a

          # 只用 small 里的 SSR 套件；避免混入 helloworld 同名包导致冲突（此处我们根本不添加 helloworld）
          ./scripts/feeds install -p small luci-app-ssr-plus
          ./scripts/feeds install -p small shadowsocksr-libev-ssr-local shadowsocksr-libev-ssr-redir
          ./scripts/feeds install -p small dns2socks microsocks ipt2socks pdnsd-alt redsocks2
          # 可选中文翻译：
          ./scripts/feeds install -p small luci-i18n-ssr-plus-zh-cn || true

          # LuCI 构建需要的主机端工具
          make package/po2lmo/host/compile V=s || true

      - name: Configure targets
        run: |
          set -e
          cd "$SDK_DIR"
          cat > .config <<'EOF'
          # LuCI 基础
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-compat=y

          # SSR-Plus 套件（来自 kenzok8/small）
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-i18n-ssr-plus-zh-cn=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir=y
          CONFIG_PACKAGE_dns2socks=y
          CONFIG_PACKAGE_microsocks=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_pdnsd-alt=y
          CONFIG_PACKAGE_redsocks2=y
          EOF
          make defconfig

      - name: Build IPKs (strict)
        run: |
          set -e
          cd "$SDK_DIR"

          # 先编 SSR-Plus（失败直接停止，并打印尾部日志）
          set +e
          make package/luci-app-ssr-plus/compile -j"$(nproc)" V=s 2>&1 | tee build_ssrplus.log
          RC=${PIPESTATUS[0]}
          if [ $RC -ne 0 ]; then
            echo "==== Tail of build_ssrplus.log ===="
            tail -n 300 build_ssrplus.log
            exit $RC
          fi
          set -e

          # 其余依赖
          make package/shadowsocksr-libev/compile -j"$(nproc)" V=s
          make package/dns2socks/compile       -j"$(nproc)" V=s
          make package/microsocks/compile      -j"$(nproc)" V=s
          make package/ipt2socks/compile       -j"$(nproc)" V=s
          make package/pdnsd-alt/compile       -j"$(nproc)" V=s
          make package/redsocks2/compile       -j"$(nproc)" V=s

          # 收集产物并做强校验
          mkdir -p ipk_out
          find bin/ -type f -name '*.ipk' -exec cp -av {} ipk_out/ \;

          if ! ls ipk_out/luci-app-ssr-plus_*.ipk >/dev/null 2>&1; then
            echo "FATAL: luci-app-ssr-plus ipk not found."
            exit 2
          fi

          echo "==> Final IPKs:"
          ls -lh ipk_out | sed 's/^/  /'

      - name: Upload IPKs (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ipk-24.10.0-x86_64-ssrplus-small
          path: ${{ env.SDK_DIR }}/ipk_out/*.ipk
