name: Build-SSRPlus-23.05.5-x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex g++ gawk gcc-multilib gettext \
            libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev swig \
            libpython3-dev aria2 jq wget curl file bc cmake ninja-build
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Download OpenWrt 23.05.5 x86_64 SDK
        run: |
          set -eux
          URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          ALT="https://downloads.cdn.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          curl -fL --retry 3 -o sdk.tar.xz "$URL" || curl -fL --retry 3 -o sdk.tar.xz "$ALT"
          tar -xJf sdk.tar.xz
          rm -f sdk.tar.xz
          SDK_DIR="$(ls -d openwrt-sdk-23.05.5-*/ | head -n1)"
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: Prepare feeds (pin 23.05) + add kenzok8/small
        working-directory: ${{ env.SDK_DIR }}
        run: |
          set -eux
          cat > feeds.conf.default <<'EOF'
          src-git packages https://git.openwrt.org/feed/packages.git;openwrt-23.05
          src-git luci https://github.com/openwrt/luci.git;openwrt-23.05
          src-git routing https://git.openwrt.org/feed/routing.git;openwrt-23.05
          src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-23.05
          src-git small https://github.com/kenzok8/small.git
          EOF

          ./scripts/feeds update -a
          # 安装全部索引（不会编译），确保依赖能被解析
          ./scripts/feeds install -a
          # 明确安装 ssr-plus 到包索引
          ./scripts/feeds install -p small luci-app-ssr-plus

      - name: HOTFIX – 彻底关闭 lucihttp 的 Lua/ucode 绑定
        working-directory: ${{ env.SDK_DIR }}
        run: |
          set -eux
          # lucihttp 的 Makefile 在 luci/contrib/package/lucihttp 下
          MF="feeds/luci/contrib/package/lucihttp/Makefile"
          test -f "$MF"
          # 强制把 cmake 里的 BUILD_LUA/BUILD_UCODE 关掉（避免找 lua.h）
          sed -i 's/BUILD_LUA=ON/BUILD_LUA=OFF/g; s/BUILD_UCODE=ON/BUILD_UCODE=OFF/g' "$MF"

      - name: Build luci-app-ssr-plus (IPK only)
        working-directory: ${{ env.SDK_DIR }}
        run: |
          set -eux
          make defconfig
          # 单包编译，方便快速出 IPK，且日志清晰
          make -j1 V=s package/feeds/small/luci-app-ssr-plus/compile

      - name: Collect artifacts
        working-directory: ${{ env.SDK_DIR }}
        run: |
          set -eux
          mkdir -p _out
          # small/luci 等 feed 产物目录
          find bin/packages -type f -name '*.ipk' -print -exec cp -f {} _out/ \;
          # 也把 .config 留作参考
          cp -f .config _out/config-23.05.5-x86_64.txt || true

      - name: Upload IPKs
        uses: actions/upload-artifact@v4
        with:
          name: ipk-ssrplus-23.05.5-x86_64
          path: ${{ env.SDK_DIR }}_out
